### ISSUE TITLE
[Bug]: Random NullPointerException on Dummy Transforms

### ISSUE THREAD

**Issue by Cupropituvanso** [apache/hop#3451] opened 2023-11-23 10:19 UTC
### Apache Hop version?

2.6

### Java version?

openjdk version "11.0.20" 2023-07-18

### Operating system

Docker

### What happened?

Hello

We have discovered a problem that cannot be directly understood, but occurs very frequently.
We are daily staring a workflow over the webservice which starts several pipelines in parallel.
And randomly, not every day and not the same pipeline one or more pipelines crashes on a dummy transform with:

2023/11/22 22:10:43 - DPK.0 - ERROR: Unexpected error
2023/11/22 22:10:43 - DPK.0 - ERROR: java.lang.NullPointerException
2023/11/22 22:10:46 - forb_transaction - Pipeline detected one or more transforms with errors.
2023/11/22 22:10:46 - forb_transaction - Pipeline is killing the other transforms!

DPK ist ein Dummy

Wenn man die betroffene Pipeline dann gleich wieder startet gibt es keine Probleme.
Wenn mehrere Pipelines betroffen sind tritt das Zeitgleich auf.

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by hansva** [comment] 2023-11-23 10:32
Can you provide a stack trace of the issue please, this information is not giving us much to work with.

**Comment by Cupropituvanso** [comment] 2023-11-23 11:19
<img width="673" alt="stacktrace" src="https://github.com/apache/hop/assets/6313389/9b4a3e60-9b18-43f6-8eb2-8d5522e9c5aa">

only in form of screenshot some weeks ago ... at the moment because of another problem, which seems to be a config error on our site we do not get pipeline logs (or even pipelines) in the hop status if a workflow runs.

**Comment by Cupropituvanso** [comment] 2023-11-23 22:32
its still warm ... 

2023/11/23 22:12:30 - DPK.0 - ERROR: Unexpected error
2023/11/23 22:12:30 - DPK.0 - ERROR: java.lang.NullPointerException
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transform.BaseTransform.putRowToRowSet(BaseTransform.java:1270)
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transform.BaseTransform.noPartitioning(BaseTransform.java:1212)
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transform.BaseTransform.handlePutRow(BaseTransform.java:1097)
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transform.BaseTransform$DefaultRowHandler.putRow(BaseTransform.java:3794)
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transform.BaseTransform.putRow(BaseTransform.java:1010)
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transforms.dummy.Dummy.processRow(Dummy.java:51)
2023/11/23 22:12:30 - DPK.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/11/23 22:12:30 - DPK.0 - 	at java.base/java.lang.Thread.run(Thread.java:829)
2023/11/23 22:12:30 - DPK.0 - Finished processing (I=0, O=0, R=44, W=44, U=0, E=0)

**Comment by sramazzina** [comment] 2023-11-24 08:24
I think the best option to investigate better on this issue is to provide a reproduction path? Can you provide that sample?

**Comment by Cupropituvanso** [comment] 2023-11-28 11:38
How should I make a reproduction plan of this? :)

**Comment by Phsacar** [comment] 2023-12-05 00:11
Hi, I am a member of cupro's team and will try to clarify our issue:
Our Workflow starts multiple pipelines in parallel.
After some time, some pipelines crash with this mentioned error - this happens only every few days.
However, when we execute the same pipeline, with the same input data a few minutes later, everything is fine (Data is processed correctly).

However, we cant really get the error to be reproducible. We have a second hop instance running that has the same error with the same pipelines. Also, as you may understand, we cant give you access to our data.

From our perspective the error seems to be completely random - we actually even considered this to be an hardware issue of our server, but we ruled that one out with testing the same instance on another server.
Is there any way we could provide you with additional info ?

**Comment by Wescley-Brasil** [comment] 2024-01-16 12:25
Hello, we recently started migrating our transformations and jobs to Apache Hop, we were previously using PDI, and in some jobs we are running into this same problem of NullPointerException on Dummy. And the worst thing is that this occurs completely randomly, this problem for me happens when running a workflow as a for.

**Comment by hansva** [comment] 2024-01-16 12:37
The issue might have been resolved with #3056 
You can test it in a test environment using an unreleased version of hop fetched from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.8.0-SNAPSHOT/)

**Comment by Wescley-Brasil** [comment] 2024-01-17 17:17
@hansva After using version 2.8 of the hop, the NullPointerException problem stopped happening, I tested it again on the same load that caused the problem before and the error was resolved. Thank you for the quick and prompt response.

**Closed** 2024-02-12 08:26 UTC
Labels: bug, P1, Transforms

**Comment by CuproAT** [comment] 2024-07-29 22:14
It took a while for us to upgrade to 2.8, but yes, the problem is solved.
