### ISSUE TITLE
[Bug]: Filter String comparisons using the = operator do not work, while using IN LIST will.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#2136] opened 2023-01-07 19:45 UTC
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

If you take a String Field with value "One" and use the equal sign to test it against another String you set to a value "One", the transform refuses even to run.   However, if you change the comparator to "IN LIST" and use a semicolon-delimited list, everything works as expected.
[Strings_using_equal_aginst_other_string.zip](https://github.com/apache/hop/files/10367075/Strings_using_equal_aginst_other_string.zip)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment] 2023-01-09 11:05
Same issue as

**Comment by sramazzina** [comment] 2023-01-09 11:06
Duplicate of #2110. Look at the temporary workaround I wrote in that issue waiting for the solution. With that applied your sample works Brandon

**Closed** 2023-01-09 14:21 UTC
Labels: bug, P3, Transforms
