### ISSUE TITLE
[Bug]: Hop Gui - unable to insert a new Simple Mapping transform

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#3974] opened 2024-05-24 13:36 UTC
### Apache Hop version?

2.8.0

### Java version?

openjdk version "21.0.2" 2024-01-16

### Operating system

Linux

### What happened?

Create a new pipeline in Hop GUI, and insert a new Simple Mapping transform. When clicking on the transform's name, or selecting it and then "Edit" on the menu, Hop GUI reports the following error:

> Oops! Unable to open dialog for this transform
> NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
> Root cause: NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null

The detailed stack trace follows:

> java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
> 	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1808)
> 	at java.base/java.util.regex.Matcher.reset(Matcher.java:461)
> 	at java.base/java.util.regex.Matcher.<init>(Matcher.java:256)
> 	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1180)
> 	at org.apache.hop.pipeline.transforms.mapping.SimpleMappingDialog.getData(SimpleMappingDialog.java:366)
> 	at org.apache.hop.pipeline.transforms.mapping.SimpleMappingDialog.open(SimpleMappingDialog.java:298)
> 	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
> 	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3400)
> 	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2192)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> 	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:96)
> 	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
> 	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:473)
> 	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)

The transform stays in place and is no longer selectable, until the pipeline is closed and restarted (with the same behaviour described above if you still try to configure it).

This doesn't seem to occur with existing pipelines with the Simple Mapping transform in it (e.g. the pipeline included among the samples).

UPDATE - A workaround, if you still need to use that transform: copy the Simple Mapping transform from another pipeline (even the one included in the samples project...) and paste in your new pipeline. You can then (somehow, still struggling) edit it to fit your needs

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by hansva** [comment] 2024-05-24 13:58
duplicate of #3809 and fixed in 2.9

**Closed by hansva** 2024-05-24 13:58 UTC
Labels: awaiting triage, bug, P2, Hop Gui, Transforms
