### ISSUE TITLE
[Bug]: Filter - Fails comparing Boolean using = against Boolean with a True value.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#2135] opened 2023-01-07 14:58 UTC
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

If you try to use a filter and = is used as the test and you define a true or false boolean on the right side, the step fails and complains about the expression.
[boolean_test_using_filter_with_equal_sign.zip](https://github.com/apache/hop/files/10366539/boolean_test_using_filter_with_equal_sign.zip)

Just run this simple hpl and you will see what I mean.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment] 2023-01-09 11:07
Duplicate of #2110 . Look at the temporary workaround specified in that issue

**Closed** 2023-01-09 14:21 UTC
Labels: bug, P3, Transforms
