### ISSUE TITLE
[Bug]: Hop Server  REST api

### ISSUE THREAD

**Issue by yunkuotianxian** [apache/hop#4151] opened 2024-07-22 11:05 UTC
### Apache Hop version?

2.9.0

### Java version?

11

### Operating system

Windows

### What happened?

How to call the interfaces of the following APIs? It's a get method, but how to pass XML into the method? On line 93 of the AddPipeServlet.doGet in the source code, the value of the StringBuilder XML is set to 'new StringBuilder' (request. getContentLength()) It will report an error because in the get method, request. getContentLength() may be -1. How should this API be called?

ADDWORKFLOW
name
addWorkflow

description
Add a workflow for execution

endPoint
GET hop/addWorkflow

Content-Type: text/xml;charset=UTF-8

parameters
xml Request body should contain xml containing workflow_configuration (pipeline and workflow_execution_configuration wrapped in pipeline_configuration tag).

example request
http://localhost:8081/hop/addWorkflow/xml=Y with XML payload

result
-

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by hansva** [comment] 2024-07-22 11:58
That get method requires content, the get will return a status after content parsing

**Comment by yunkuotianxian** [comment] 2024-07-23 02:46
> That get method requires content, the get will return a status after content parsing

Can you provide a detailed introduction on how to operate it ？

**Comment by hansva** [comment] 2024-07-23 07:19
We don't suggest manually crafting these calls, you can use the CLI to start pipelines on a remote server.
The code we use to send pipelines to the server can be found [here](https://github.com/apache/hop/blob/ab684257bde84cc605aa681b3e65b04a9f856c39/engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java#L99)

Closing this ticket as it is not a bug but a question.
Questions can be sent to our Mailing lists: https://hop.apache.org/community/mailing-list/

**Closed by hansva** 2024-07-23 07:19 UTC
Labels: awaiting triage, bug, P3, Hop Server
