### ISSUE TITLE
[Task]: Weblate is not referenced anywhere on the site

### ISSUE THREAD

**Issue by nadment** [apache/hop#3998] opened 2024-05-29 19:36 UTC
### What needs to happen?

Weblate is not referenced anywhere on the site, so we should write a short paragraph explaining why. 

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by hansva** [comment] 2024-05-29 20:22
this page should be changed to instruct on how to use weblate
https://hop.apache.org/community/contribution-guides/translation-contribution-guide/

**Comment by hansva** [comment] 2024-05-29 20:22
.take-issue

**Comment by hansva** [comment] 2024-06-10 06:04
duplicate of #2217

**Closed** 2024-06-10 06:12 UTC
Labels: task, P3, Documentation
