### ISSUE TITLE
[Bug]: Delete command is deleting wrong action

### ISSUE THREAD

**Issue by maxbobse** [apache/hop#2567] opened 2023-03-15 09:14 UTC
### Apache Hop version?

2.3

### Java version?

jdk-16.0.1.9

### Operating system

Windows

### What happened?

On Windows, I am drawing a box around an action (Dummy) in my pipeline to select it. Now I left click on another action (Dummy 2) to bring up the context menu and select Delete. Now it is deleting the action Dummy that I previously selected and not the one that I opened the context menu against (Dummy 2).

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by ep9io** [comment] 2024-12-18 14:20
I experienced the same issue on Linux during the year and it was a cause of pain.  I wanted to check to see if the issue was still present, but looks like it isn't and it might be resolved.

I can reproduce the issue on version 2.8.0 (2024-02-28 03.31.08), but can't on the latest master 2.12.0-SNAPSHOT (December 2024).

### Steps taken:

1. Create a blank pipeline
2. Create Dummy1
3. Create Dummy2
4. Highlight Dummy1
5. Left-click on Dummy2
6. Click on the Delete option

### Results:

- v2.8.0 deletes Dummy1 when the intention is to delete Dummy2
- v2.12.0-SNAPSHOT deletes Dummy2 as intended.

### Environment tested on:

- 2.8.0 is on Ubuntu 22.04.4 LTS (Gnome) and running on X11. 
- 2.12.0-SNAPSHOT is on Fedora Linux 39 (Workstation Edition) and running on Wayland.

NOTE: 
- The issue can't be reproduced on 2.12.0-SNAPSHOT with or without `GDK_BACKEND=x11` switched on, suggesting that the issue is not caused by being on Wayland or not.
- I haven't tested 2.12 snapshot on the Ubuntu setup, but considering that the original ticket reports it on Window makes me think it's been resolved at some stage in between 2.8 and 2.12 on master.

### Evidence
Steps 1 to 5 where performed.

Below is are screenshots from 2.8, notice how Dummy1 is still selected/highlighted and the actions dialog shows Dummy2.  Clicking delete will remove Dummy1 instead of Dummy2.

![image](https://github.com/user-attachments/assets/fc612321-0d0a-4a40-a907-98fc854f15f8)
![image](https://github.com/user-attachments/assets/2ed6c6d8-e0f6-4592-9061-d018fdc65493)


Below is a screenshot from 2.12-SNAPSHOT, notice how Dummy2 is selected when the actions dialog for it is shown.  Clicking delete will remove Dummy2 as intended.

![image](https://github.com/user-attachments/assets/4b042153-406a-40fd-8d30-f813b2109fe2)
![image](https://github.com/user-attachments/assets/86f2997b-665a-4bff-9cb6-5ded4451f6a4)

**Comment by hansva** [comment] 2024-12-18 17:41
this was resolved by #4578 in 2.11 release

**Closed by hansva** 2024-12-18 17:41 UTC
Labels: awaiting triage, bug, P2, Hop Gui
